### ISSUE TITLE
FacebookLogin.login() Error performing query [extra].

### ISSUE THREAD

**Issue by eduboxgithub** [capacitor-community/facebook-login#15]
**Describe the bug**
When doing a call to the method FacebookLogin.login() we get an error in the catch:

```
SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: 
    at Object.fromNative (capacitor-runtime.js:226)
    at <anonymous>:1:18
```

Logcat error output when Login() is called:

```
2020-09-25 18:22:58.898 2803-2998/com.edubox.app D/Capacitor/FacebookLogin: Entering getCurrentAccessToken()
2020-09-25 18:22:58.898 2803-2998/com.edubox.app D/Capacitor/FacebookLogin: getCurrentAccessToken: accessToken is null
2020-09-25 18:22:58.913 2803-2803/com.edubox.app I/Capacitor/Console: File: http://localhost/main-es2015.js - Line 6272 - Msg: FacebookLogin.getCurrentAccessToken:  [object Object]
2020-09-25 18:22:58.913 2803-2998/com.edubox.app D/Capacitor/FacebookLogin: Entering login()
2020-09-25 18:22:58.934 2803-2803/com.edubox.app D/Capacitor: App paused
2020-09-25 18:23:00.152 2803-2803/com.edubox.app D/Capacitor/FacebookLogin: Entering handleOnActivityResult(64206, -1)
2020-09-25 18:23:00.154 2803-2803/com.edubox.app E/Capacitor/FacebookLogin: LoginManager.onError
    SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: 
        at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:219)
        at com.facebook.login.LoginManager$1.onActivityResult(LoginManager.java:174)
        at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:91)
        at com.getcapacitor.community.facebooklogin.FacebookLogin.handleOnActivityResult(FacebookLogin.java:137)
        at com.getcapacitor.Bridge.onActivityResult(Bridge.java:776)
        at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:214)
        at android.app.Activity.dispatchActivityResult(Activity.java:8310)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5056)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2020-09-25 18:23:00.154 2803-2803/com.edubox.app D/Capacitor: Sending plugin error: {"save":false,"callbackId":"2090982","pluginId":"FacebookLogin","methodName":"login","success":false,"error":{"message":"SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: "}}
2020-09-25 18:23:00.154 2803-2803/com.edubox.app D/Capacitor/FacebookLogin: onActivityResult succeeded
2020-09-25 18:23:00.155 2803-2803/com.edubox.app D/Capacitor/App: Firing change: true
2020-09-25 18:23:00.155 2803-2803/com.edubox.app D/Capacitor/App: No listeners found for event appStateChange
2020-09-25 18:23:00.169 2803-2803/com.edubox.app D/Capacitor: App resumed
2020-09-25 18:23:00.206 2803-2803/com.edubox.app D/Capacitor/Network: No listeners found for event networkStatusChange
2020-09-25 18:23:00.211 2803-2803/com.edubox.app I/Capacitor/Console: File: http://localhost/main-es2015.js - Line 6260 - Msg: Error logging into Facebook Error: SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: 
```

**To Reproduce**

```
const loginFacebook = ():Promise<AuthSession> =>
{
            return new Promise((resolve, reject) => 
            {
                FacebookLogin.login({ permissions: ['public_profile', 'email'] }).then((authdata: FacebookLoginResponse) =>
                {
                    console.log("FacebookLogin.login authdata: ",  authdata);

                    getFacebookUserDataAndAuth(authdata).then((session:AuthSession) => 
                    {
                        resolve(session);
                    })
                    .catch(error => 
                    {		
                        reject("LOGIN_ERROR");
                    });
                })
                .catch(error => 
                {
                    console.log('Error logging into Facebook', error);

                    //message: "SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]:

                    reject("LOGIN_ERROR");
                });
});
```

**Expected behavior**
It should resolve the request with the auth data.

**Screenshots**
![image](https://user-images.githubusercontent.com/13800439/94294608-f96b0700-ff57-11ea-9d75-85e2fe7ccfab.png)

**Smartphone (please complete the following information):**
 - Device: OnePlus5T
 - OS: Android 10
 - Browser Capacitor + WebView latest version

**Comment by eduboxgithub** [comment]
Sorry about this issue... The problem was the application id... it was wrongly set.
